# Electric Capital crypto-ecosystems submission snippet
# Updated to reflect the latest changes in the master branch.

[[project]]
name = "AlgoSafe"
description = "Algorand multi-signature and time-locked wallet (React + TypeScript)."
homepage = "https://github.com/NagasivaKumari/Algorand-"
license = "MIT"
category = "wallet"
tags = ["algorand", "wallet", "multisig", "timelock", "security"]

  [[project.repo]]
  url = "https://github.com/NagasivaKumari/Algorand-"
  branch = "master"
